name: Compare Screenshots - Windows DX12

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * *'
  
env:
  PER_PAGE: 17

jobs:
  take-screenshots:
    name: Take Screenshots
    runs-on: windows-latest
    strategy:
      matrix:
        # if all examples are not built, add a new page here
        page: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:

      - name: Checkout Bevy main branch
        uses: actions/checkout@master
        with:
          repository: 'bevyengine/bevy'
          ref: 'main'

      # temporary: fetch tools from PR
      - name: Checkout Bevy Tools
        uses: actions/checkout@master
        with:
          repository: 'mockersf/bevy'
          ref: 'example-showcase-can-remove-desktop-mode'
          path: 'bevy-tools'
      - name: Copy Bevy tools to main
        run: |
          rm -r tools
          cp -r bevy-tools/tools/ tools

      - name: apply patch
        run: |
          git apply --verbose tools/example-showcase/remove-desktop-app-mode.patch

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Take Screenshots
        run: |
          cargo run -p example-showcase -- --page ${{ matrix.page }} --per-page ${{ env.PER_PAGE }} run --screenshot --in-ci --ignore-stress-tests

      - name: Upload Generated Files
        uses: actions/upload-artifact@v3
        with:
          name: screenshots-windows-${{ matrix.page }}
          path: screenshots

  send-to-percy:
    name: Prepare Screenshots Update PR
    runs-on: ubuntu-latest
    needs: take-screenshots
    steps:
      
      - name: Clone bevy-website repo
        uses: actions/checkout@master

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Move examples to the correct folder
        run: |
          mkdir screenshots-windows
          for file in screenshots-windows-*
          do
            rsync -a $file/* screenshots-windows/
            rm -rf $file
          done

      - name: Send to Percy
        run: |
          npm install -g @percy/cli@latest
          npx percy upload screenshots-windows
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_WINDOWS_DX12 }}
