name: Compare Screenshots

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * *'
  
env:
  PER_PAGE: 17

jobs:
  take-screenshots:
    name: Take Screenshots
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # if all examples are not built, add a new page here
        page: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:

      - name: Checkout Bevy main branch
        uses: actions/checkout@master
        with:
          repository: 'bevyengine/bevy'
          ref: 'main'

      # temporary: fetch tools from main branch
      - name: Checkout Bevy Tools
        uses: actions/checkout@master
        with:
          repository: 'mockersf/bevy'
          ref: 'main'
          path: 'bevy-tools'
      - name: Copy Bevy tools to main
        run: |
          rm -r tools
          cp -r bevy-tools/tools/ tools
          rm -r bevy-tools

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Bevy dependencies
        run: |
          sudo apt-get update;
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq \
            libasound2-dev libudev-dev;

      - name: install xvfb, llvmpipe and lavapipe
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:oibaf/graphics-drivers -y
          sudo apt-get update
          sudo apt install -y xvfb libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers

      - name: Take Screenshots
        run: |
          xvfb-run cargo run -p example-showcase -- --page ${{ matrix.page }} --per-page ${{ env.PER_PAGE }} run --screenshot --in-ci --ignore-stress-tests

      - name: Upload Generated Files
        uses: actions/upload-artifact@v3
        with:
          name: screenshots-linux-${{ matrix.page }}
          path: screenshots

  send-to-percy:
    name: Prepare Screenshots Update PR
    runs-on: ubuntu-latest
    needs: take-screenshots
    steps:
      
      - name: Clone bevy-website repo
        uses: actions/checkout@master

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Move examples to the correct folder
        run: |
          mkdir screenshots-linux
          for file in screenshots-linux-*
          do
            rsync -a $file/* screenshots-linux/
            rm -rf $file
          done

      - name: Send to Percy
        run: |
          npm install -g @percy/cli@latest
          npx percy upload screenshots-linux
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_LINUX_VULKAN }}
