name: Test

on:
  workflow_dispatch:
  
jobs:
  update-website:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: "results"
          path: "results"
      - name: Log errors
        shell: bash
        run: |
          echo "Errors:"
          cat results/202307271925-0566e73af460b9d128354a20970b1e1e0cc3b719/Windows-no_screenshots
          echo "::warning title=no screenshots::`cat results/202307271925-0566e73af460b9d128354a20970b1e1e0cc3b719/Windows-no_screenshots | tr '\n' '', '`"

          