name: Test

on:
  workflow_dispatch:
  
jobs:
  update-website:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "results"
          path: "results"
      - name: Log errors
        shell: pwsh
        run: |
          if (Get-Content results/202307271925-0566e73af460b9d128354a20970b1e1e0cc3b719/${{ runner.os }}-no_screenshots) {
            perl -p -e 's/(.*) - [.0-9]*\n/\1, /g' results/202307271925-0566e73af460b9d128354a20970b1e1e0cc3b719/${{ runner.os }}-no_screenshots > cleaned
            $no_screenshots = Get-Content .\cleaned -Raw
            echo "::warning title=No Screenshots ${{ runner.os }}::$no_screenshots"
          }
          if (Get-Content results/202307271925-0566e73af460b9d128354a20970b1e1e0cc3b719/${{ runner.os }}-failures) {
            perl -p -e 's/(.*) - [.0-9]*\n/\1, /g' results/202307271925-0566e73af460b9d128354a20970b1e1e0cc3b719/${{ runner.os }}-failures > cleaned
            $failures = Get-Content .\cleaned -Raw
            echo "::error title=Failed To Run ${{ runner.os }}::$failures"
          }
