name: Test

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: Force

jobs:
  job_a:
    runs-on: ubuntu-latest
    outputs:
      null_value: ${{ steps.b.outputs.never }}
    steps:
      - id: b
        run: echo "We opt not to set any output at this time"
  job_b:
    runs-on: ubuntu-latest
    needs: job_a
    if: needs.job_a.outputs.null_value || github.event.inputs.force == 'true'
    steps:
      - run: echo "We've ensured this job will be skipped"
  job_c:
    runs-on: ubuntu-latest
    needs: [job_a, job_b]
    steps:
      - run: echo "This won't run, even though the IF condition evaluates true."
