name: Test

on:
  workflow_dispatch:

jobs:

  update-website:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: "results"
          path: "results"
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build website
        run: |
          cargo run -- results
          mkdir site
          mv index.html site/index.html
      - name: Store generated html
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
